#!/bin/bash -e
# bootstrap for macOS

check_cmd() {
    command -v "$1" > /dev/null 2>&1
}

need_cmd() {
    if ! check_cmd "$1"; then
        err "command '$1' not found"
    fi
}

msg() {
    printf 'bootstrap: %s\n' "$1"
}

err() {
    msg "$1" >&2
    exit 1
}

macos() {
  check_cmd nix || {
    msg "installing Nix using Determinate Systems installer"
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
  }

  need_cmd nix-channel

  nix-channel --add https://nixos.org/channels/nixpkgs nixpkgs
  nix-channel --update
  nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager

  # nix-darwin installer no longer needed on flake-based systems
}

if [ "$(uname)" == "Darwin" ]; then
  macos $@
else
  echo "Unsupported operating system: $(uname)"
fi 
