#!/bin/bash -e
# bootstrap for macOS

check_cmd() {
    command -v "$1" > /dev/null 2>&1
}

need_cmd() {
    if ! check_cmd "$1"; then
        err "command '$1' not found"
    fi
}

msg() {
    printf 'bootstrap: %s\n' "$1"
}

err() {
    msg "$1" >&2
    exit 1
}

macos() {
  check_cmd nix || {
    msg "installing Nix using Determinate Systems installer"
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
  }

  profile_sh=/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  [ -f $profile_sh ] && source $profile_sh

  need_cmd nix

  #need_cmd nix-channel

  #msg "adding nixpkgs channel"
  #nix-channel --add https://nixos.org/channels/nixpkgs nixpkgs

  #msg "adding home-manager channel"
  #nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager

  #msg "updating channels"
  #nix-channel --update

  # nix-darwin installer no longer needed on flake-based systems
}

if [ "$(uname)" == "Darwin" ]; then
  macos $@
else
  echo "Unsupported operating system: $(uname)"
fi 
